version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: go-rest-api-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5438:5432"
    volumes:
        - go-rest-api-db:/var/lib/postgresql/data
volumes:
    go-rest-api-db: