# @name createUser
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "JaneDoe44",
  "email": "janedoe@gmail.com",
  "password": "password123"
}

###

# @name loginUser
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "janedoe@gmail.com",
  "password": "password123"
}


###

# @name getUserById
GET http://localhost:8080/users/f538c8aa-2451-4a3d-8a64-b7111e72a904
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTcxODk2MzUsInVzZXJfaWQiOiJmNTM4YzhhYS0yNDUxLTRhM2QtOGE2NC1iNzExMWU3MmE5MDQifQ.4icOJukeMt55YLw9jz3nRSBZdWh5TxYik3kM7k41_5Q

# Heatlth Check
GET http://localhost:8080/health