# Heatlth Check
GET http://localhost:8080/health

###

#Create User
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "JaneDoe44",
  "email": "janedoe@gmail.com",
  "password": "password123"
}

###

#Get User by ID
GET http://localhost:8080/users/93a4f90c-74e8-4a97-a563-422ecde5e2bd

###
#Login User
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "janedoe@gmail.com",
  "password": "password123"
}