name: Go CI/CD

# This workflow will build and test a Go project
# For more information see: https://docs.github.com/actions/languages/go

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main"]
    pull_request:
        branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Install migrate tool
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Build
        run: make build

      - name: Run unit tests
        run: make test-unit

      - name: Run integration tests
        run: make test-integration